runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: charlie
  CLOUD_SQL_PASSWORD: 215585274Cb
  CLOUD_SQL_DATABASE_NAME: sales
  CLOUD_SQL_CONNECTION_NAME: 35.237.252.223

# handlers:
# - url: /.*
#   script: auto